name: Update Social Preview
on:
  deployment_status:

jobs:
  screenshot:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'github-pages'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright
        run: |
          npm install -g playwright
          npx playwright install chromium --with-deps

      - name: Take Screenshot with Playwright
        run: |
          npx playwright screenshot --wait-for-timeout 5000 https://johannesl2.github.io/slot-game/ assets/screenshot.png

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/screenshot.png
          git commit -m "chore: automated screenshot update" || true
          git push